services:
  vector:
    image: timberio/vector:0.39.0-debian
    restart: always
    ports:
      - "8686:9000"
    volumes:
      - ./vector/data:/etc/vector/data
      - ./vector/conf/vector.yaml:/etc/vector/vector.yaml